export const subjects = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Computer Science",
  "Programming",
  "Serbian Language and Literature",
  "English Language",
  "German Language",
  "Italian Language",
  "French Language",
  "Spanish Language",
  "Latin Language",
  "Biology",
  "History",
  "Geography",
  "World Around Us",
  "Something else",
];
